### ISSUE TITLE
How can I refer to this project to complete my own website construction

### ISSUE THREAD

**Issue by eryajf** [z3by/vuepress-tools#274]
Hello, The design of this project is great, I really like it.
I have a project，Its: https://github.com/eryajf/awesome-ops

I want to combine the framework of your project and make the content of my project like this. How should I start。

I am currently trying to run it locally, but I have encountered an error。

when I run: `yarn dev`, I get:

```
$ yarn dev
yarn run v1.22.22
$ nuxt
ℹ Parsed 837 files in 3,2 seconds                                                                                                                                  @nuxt/content 08:41:21

   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.15.8                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   client-side          │
   │   ▸ Target:      static               │
   │                                       │
   │   Listening: http://localhost:3000/   │
   │                                       │
   ╰───────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                              08:41:22
ℹ Initial build may take a while                                                                                                                                                 08:41:22
ℹ Discovered Components: .nuxt/components/readme.md                                                                                                                              08:41:22
✔ Builder initialized                                                                                                                                                            08:41:22
✔ Nuxt files generated                                                                                                                                                           08:41:22

 WARN  Browserslist: caniuse-lite is outdated. Please run:                                                                                                                       08:41:22
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating


● Client █████████████████████████ compiling (0%)



 ERROR  Error: error:0308010C:digital envelope routines::unsupported                                                                                                             08:41:22
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9

node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/eryajf/tmp-eryajf/test/vuepress-tools/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.20.3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by eryajf** [comment]
I understand, I switched the node version to 14 and now it can run normally
